package:
  name: pomme
  version: "0.0.16"

about:
  home: "https://github.com/Magritte-code/pomme"
  license: GPLv3
  license_file: LICENSE
  summary: Probabilistic 3D Reconstruction of Spectral Line Observations.

requirements:
  build:
    - python={{ python_version }}
    - setuptools
    - wheel
    - pip

  run:
    - python={{ python_version }}
    - matplotlib
    - astroquery
    - radio-beam
    - ipywidgets
    - pytorch>=2.0.0
    - astropy
    - numpy
    - numba
    - tqdm
    - h5py

source:
  path: ../