package:
  name: p3droslo
  version: "0.0.10"

about:
  home: "https://github.com/Magritte-code/p3droslo"
  license: GPLv3
  license_file: LICENSE
  summary: Probabilistic 3D Reconstruction of Spectral Line Observations.

requirements:
  build:
    - python={{ python_version }}
    - setuptools
    - wheel
    - pip

  run:
    - python={{ python_version }}
    - matplotlib
    - astroquery
    - ipywidgets
    - pytorch
    - astropy
    - numpy
    - numba
    - tqdm
    - h5py

source:
  path: ../