package:
  name: p3droslo
  version: "0.0.8"

about:
  home: "https://github.com/Magritte-code/p3droslo"
  license: GPLv3
  license_file: LICENSE
  summary: Probabilistic 3D Reconstruction of Spectral Line Observations.

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - wheel
    - pip

  run:
    - python
    - matplotlib
    - astroquery
    - ipywidgets
    - pytorch
    - astropy
    - numpy
    - numba
    - tqdm